package com.jbeli.messagerie.salonDiscussion;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.*;
import lombok.*;
import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@ApiModel("Contains all the attributes required under chat room entity")
public class SalonDiscussion {

    @ApiModelProperty("This the unique ID of the chat room , will be generated by the system")
    private Integer id ;

    @ApiModelProperty("the title of the chat room")
    private String titre;

   // @ManyToMany(mappedBy = "salonDiscussions")
    //private Set<Utilisateur> utilisateurss = new HashSet<>();
    //@Getter
    //private List<Utilisateur> utilisateurs;

   // @OneToMany(mappedBy = "salonDiscussion")
    //private List<UtilisateurSalonDiscussion> utilisateurSalonDiscussions;



}
