package com.jbeli.messagerie.salonDiscussion;


import com.jbeli.gestion.utilisateurs.utilisateur.Utilisateur;
import com.jbeli.messagerie.messages.Messages;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

import java.util.HashSet;
import java.util.Set;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@ApiModel("Contains all the attributes required under chat room entity")
public class SalonDiscussion {

    @ApiModelProperty("This the unique ID of the chat room , will be generated by the system")
    private Integer id ;

    @ApiModelProperty("the title of the chat room")
    private String titre;

    @OneToMany(mappedBy = "salon", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Messages> messages = new ArrayList<>();

    @ManyToMany(mappedBy = "salonDiscussions")
    private Set<Utilisateur> utilisateurss = new HashSet<>();

    @Getter
    private List<Utilisateur> utilisateurs;




}
