package com.jbeli.gestion.utilisateurs.societe;

import com.jbeli.gestion.utilisateurs.recruteur.Recruteur;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@ApiModel("Contains all the attributes required under company entity")
public class Societe {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("This the unique ID of the interview , will be generated by the system")
    private Integer id ;

    @ApiModelProperty("the name of the company")
    private String Nom;

    @ApiModelProperty("the email of the company")
    private String email;

    @OneToOne(mappedBy = "societe")
    private Recruteur recruteur ;

}
