
server:
  port: 8081

spring:
  application:
    name: common-service
  datasource:
    url: jdbc:postgresql://localhost:5432/evaluation?createDatabaseIfNotExist=true
    username: postgres
    password: Emna@2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
