package com.jbeli.messagerie.messages;

import com.jbeli.messagerie.salonDiscussion.SalonDiscussion;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.persistence.*;
import lombok.*;
import java.util.Date;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
@ApiModel("Contains all the attributes required under Messages entity")
public class Messages {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("This the unique ID of the messages , will be generated by the system")
    private Integer id ;

    @ApiModelProperty(" date of the message")
    private Date date;

    @ApiModelProperty(" the message")
    private String message;

    @ApiModelProperty(" status of the message")
    private EtatEnum etat;

    @ManyToOne
    @JoinColumn(name = "salon_id")
    private SalonDiscussion salon;



}
